# Generated by Django 4.2.3 on 2023-07-31 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=30, unique=True)),
                ('cod', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ('dept',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, unique=True)),
                ('cod', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('unidade',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('documento', models.IntegerField()),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('rev', models.IntegerField(default=0, verbose_name='Revisão')),
                ('slug', models.SlugField(default='')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacao.departamento')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacao.tipodocumento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacao.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('doc', models.FileField(blank=True, null=True, upload_to='docfiles/', verbose_name='documento')),
                ('bmf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacao.documento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
